# Generated by Django 4.0.4 on 2022-12-28 21:36

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('AccountNum', models.CharField(max_length=12)),
                ('CardNum', models.CharField(max_length=16)),
                ('TotalBalance', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='CharityBox',
            fields=[
                ('CharityBoxID', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField(unique=True)),
                ('Type', models.CharField(choices=[('BIG-PLASTIC', 'Big-Plastic'), ('SMALL-PLASTIC', 'Small-Plastic'), ('BIG-STEEL', 'Big-Steel'), ('SMALL-STEEL', 'Small-Steel')], max_length=50)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('Archive', 'Archive')], default='ACTIVE', max_length=10)),
                ('StartDate', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CharityBoxReceiver',
            fields=[
                ('CharityBoxReceiverID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('NationalCode', models.CharField(max_length=10, unique=True)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('CreatingDate', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['LastName', 'FirstName'],
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('HelperID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=55)),
                ('LastName', models.CharField(max_length=55)),
                ('NationalCode', models.CharField(max_length=10, unique=True)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Address', models.TextField()),
                ('PostCode', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'deactive')], default='ACTIVE', max_length=10)),
                ('TotalHelped', models.BigIntegerField()),
                ('CreatingDate', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['LastName', 'FirstName'],
            },
        ),
        migrations.CreateModel(
            name='PersonInNeed',
            fields=[
                ('PersonInNeedID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('NationalCode', models.CharField(max_length=10, unique=True)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Address', models.TextField(max_length=60)),
                ('PostCode', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'deactive')], default='ACTIVE', max_length=10)),
                ('TotalMoneyReceived', models.BigIntegerField(default=0)),
                ('CreateDate', django_jalali.db.models.jDateField(auto_now=True)),
            ],
            options={
                'ordering': ['LastName', 'FirstName'],
            },
        ),
        migrations.CreateModel(
            name='PayToCharity',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.BigIntegerField()),
                ('PaymentDate', django_jalali.db.models.jDateField(auto_now=True)),
                ('PaymentType', models.CharField(blank=True, choices=[('CART', 'Cart'), ('CASH', 'Cash'), ('BOX', 'Box')], default='BOX', max_length=10, null=True)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, null=True)),
                ('HasPaid', models.BooleanField(default=True)),
                ('CardNumber', models.CharField(blank=True, max_length=16, null=True)),
                ('Bank', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.account')),
                ('CharityBoxID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.charitybox')),
                ('CharityBoxReceiverID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.charityboxreceiver')),
                ('HelperID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.helper')),
            ],
            options={
                'ordering': ['PaymentDate'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('DonationID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.BigIntegerField()),
                ('Date', django_jalali.db.models.jDateField(auto_now=True)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.account')),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.personinneed')),
            ],
        ),
        migrations.AddField(
            model_name='charitybox',
            name='HelperID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='management.helper'),
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('AssignID', models.AutoField(primary_key=True, serialize=False)),
                ('AssignDate', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('CharityBoxID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.charitybox')),
                ('CharityBoxReceiverID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.charityboxreceiver')),
            ],
        ),
    ]
